#!/bin/sh
#
# pick changed files from git status
#
# requires:
# - fzf (https://github.com/junegunn/fzf)
# - bat (change to your liking) (https://github.com/sharkdp/bat)

preview_cmd="bat --color=always --line-range=:500"
history_file="$HOME/.cache/hx-git-changes-history"

# Ensure history file exists
[ -f "$history_file" ] || touch "$history_file"

# List changed files in the git repository and allow user to select using fzf
git status --porcelain |
    awk '{print $2}' |
    fzf --multi --height 100% --prompt 'git changes> ' \
        --preview "$preview_cmd {}" --history="$history_file" \
        --bind "ctrl-d:preview-page-down,ctrl-u:preview-page-up" |
    while read -r file; do
        hx-utils open -d top "${file}"
    done
