#!/usr/bin/env bash

# Determine the script's directory
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
MODULES_DIR="$(dirname "${SCRIPT_DIR}")/hx-utils-modules"

# Source configuration
source "${MODULES_DIR}/config.sh"

# Source modules
source "${MODULES_DIR}/hx-open.sh"
source "${MODULES_DIR}/hx-harpoon.sh"

source "${MODULES_DIR}/hx-integration.sh"

# Function to display help message
show_help() {
  echo "Usage: hx-utils [COMMAND] [OPTIONS]"
  echo ""
  echo "Available commands:"
  echo "  blame               Show git blame information"
  echo "  explorer            Open file explorer"
  echo "  grep                Search for a pattern in files"
  echo "  browse              Open the git repository URL in browser"
  echo "  copy-permalink      Copy the git repository URL to clipboard"
  echo "  git-files           List files tracked by git"
  echo "  git-changed-files   List files changed in git"
  echo "  open                Open a file in Helix editor"
  echo "  harpoon             Open Helix Harpoon"
  echo "  help                Show this help message"
}

# Main function to handle command routing
main() {
  case "$1" in
  blame | explorer | grep | browse | copy-permalink | git-files | git-changed-files | open | harpoon)
    hx_integration "$@"
    ;;
  help)
    show_help
    ;;
  *)
    echo "Unknown command: $1"
    show_help
    exit 1
    ;;
  esac
}

# Run main function
main "$@"
